### ISSUE TITLE
Trigger input doesn't work in Betweener Library

### ISSUE THREAD

**Issue by KyleWerle** [jkrame1/SAIC-Converter#1]
Trigger inputs don't work in Betweener library. Line 263 of Betweener.h should be 
`Bounce trig1 = Bounce();` for Bounce2 library. After changing was still not reading triggers correctly.

Have already checked hardware using both Bounce library and Bounce2 library.

**Comment by kschaffer** [comment]
Did you use the Betweener begin function before trying this?  The point of using the Bounce2 library is that it lets this syntax work... you can make a bounce object and separately initialize it.  I have tested this, e.g. using the betweener_hardware_tests sketch and the trigger inputs are fine.  

To further debug - can you tell me if you tried the betweener_hardware_tests sketch, and if this failure occurred in that case?  And/or, send me the sketch you're using?

**Comment by jkrame1** [comment]
I took a quick look and, as K said, it looks like you may be missing this in the setup function:

 b.begin();

**Comment by jkrame1** [comment]
I'm loving the idea of this program! 

I have been able to test it out a little bit and I can confirm that using the begin function in your setup does make the triggers function as expected. If you can confirm that works for you then we can close this issue.

On another note, I just wanted to let you know that it looks like you are writing values to the DAC that have been scaled for MIDI, so your CV range is very small. And your gates don't show up as expected, as they should be 0 or 4095 instead of 0 or 1. You should write CV values between 0 - 4095 to the DAC, and 0 - 127 for MIDI.

**Comment by KyleWerle** [comment]
Adding `b.begin();` fixed this issue. Thanks for the help! 
Excited to keep working on it.
